[package]
name = "nocommit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grep = "0.2"
grep-searcher = "0.1"
termcolor = "1.2"
